### ISSUE TITLE
Update to latest test cycle deployment

### ISSUE THREAD

**Issue by umamianon** [Arbi-s/umami-v2#29]
Sent these last night but just want to keep them together on Issues:
vault addr: 0x0x581aed91F5D4A796031d524d46FD6beadc088A76
API staging url: https://metrics-ai8ai5kxl-umami-finance-team.vercel.app/

**Comment by 0xdapper** [comment]
These changes are already made:
https://github.com/Arbi-s/umami-v2/blob/236619a8c67fc555a40d4d7315f1f6a61250b9e0/src/constants/index.ts#L88
https://github.com/Arbi-s/umami-v2/blob/236619a8c67fc555a40d4d7315f1f6a61250b9e0/src/constants/index.ts#L129
